name: Create an issue
description: Creates a new issue using a template with front matter.
runs:
  using: node16
  main: dist/index.js
branding:
  icon: alert-circle
  color: gray-dark
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: >
      If you want to create issue on a different repository, you can using a personal access token (PAT).
      
      [Learn how to create a personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
    default: ${{ github.token }}
  assignees:
    description: GitHub handle of the user(s) to assign the issue (comma-separated)
    required: false
  milestone:
    description: Number of the milestone to assign the issue to
    required: false
  filename:
    description: The name of the file to use as the issue template
    default: .github/ISSUE_TEMPLATE.md
    required: false
  update_existing:
    description: Update an open existing issue with the same title if it exists
    required: false
  search_existing:
    description: Existing types of issues to search for (comma-separated)
    required: false
    default: open
outputs:
  number:
    description: Number of the issue that was created
  url:
    description: URL of the issue that was created
